# Generated by Django 4.2.1 on 2023-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True)),
                ('Valor', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Unidades', models.IntegerField(null=True)),
            ],
        ),
    ]
